### ISSUE TITLE
cmnPath should consistently use DirectorySeparator

### ISSUE THREAD

**Issue by pkazanzides** [jhu-cisst/cisst#102]
cmnPath defines a method DirectorySeparator, which returns "\\" on Windows and "/" otherwise, but the code contains many hard-coded uses of "/" (or '/').

**Comment by adeguet1** [comment]
It seems that Windows supports '/' except for DOS/terminal command lines (used as command flag, e.g.  `/h`).  I don't think we use `cmnPath` for any `exec` command so maybe the solution is to adopt '/' for everything.  Alternatively, we can fix `cmnPath` to call the `DirectorySeparator` method (and all other packages using `cmnPath`) to be consistent across cisst/SAW.

**Comment by pkazanzides** [comment]
You can get some weird looking paths on Windows, such as `C:\Program Files\myprogram/subdir`, but it works.  In this case, the first part of the path came from `cmnPath::GetWorkingDirectory()`. I imagine a similar situation would happen using `cmnPath::GetCisstRoot()`.

But, there are some issues that would not actually be solved by changing to `DirectorySeparator`.  For example, in `FindWithSubdirectory`, there is a check for `filename[0] == '/'` to determine whether it is an absolute path.  On Windows, an absolute path could be something like `C:\Program Files\...`.

Following are two suggestions:

1. Systematically replace all `\\` by `/`, for example, by using `std::replace`, at least for methods such as `GetWorkingDirectory` and `GetCisstRoot` that interface with the OS.
2. Create an `isAbsolutePath` method that (on Windows) looks for the pattern `"X:/"` (or `"X:\\"`), where `X` is the drive letter (A-Z), in addition to `'/'` or `'\\'` as the first character.

**Comment by pkazanzides** [comment]
Closing this issue for now, since `cmnPath` was updated to handle absolute paths. When building paths, it is fine to consistently use '/' because that will work on all platforms. But, when parsing paths on Windows, need to be aware that '/' or '\\' can be used, and also need to take into account possible drive letter (e.g., "C:").
