### ISSUE TITLE
vector.XYZ() * mtsDouble() compilation error 

### ISSUE THREAD

**Issue by marcinbalicki** [jhu-cisst/cisst#18]
```c++

  vct5 v5a;
  vct5 v5b;
  mtsDouble d;
  v5a.XYZ() = v5b.XYZ() * d;   //fails

//error: Invalid operands to binary expression ('vctFixedSizeVectorRef<double, 3, 1L>' and 'mtsDouble' (aka 'mtsGenericObjectProxy<double>'))

 // the following works:
v5a.XYZ() = v5b.XYZ() * d.Data
```

**Comment by pkazanzides** [comment]
The plan is to obsolete `mtsDouble`.  Instead, you would just use `double` and the software would find the methods it needs from `cmnData<double>`.

**Comment by adeguet1** [comment]
Should we close this issue?

**Comment by marcinbalicki** [comment]
Related note: Not sure if all the data types are automatically wrapped.

Here is an example:

roBehaviorSinusNavControl.h:
void SetMat(const vctDoubleMat &mat) { m = mat};

roBehaviorSinusNavControl.cpp
providedInterface->AddCommandWrite(&roBehaviorSinusNavControl::SetMat,
this, "SetMat");

error:
function mtsGenericObjectProxyBase<vctDynamicMatrix<double> >::Services()
const: error: undefined reference to
'mtsGenericObjectProxy<vctDynamicMatrix<double> >::ClassServices()'

function vtable for mtsGenericObjectProxy<vctDynamicMatrix<double> >:
error: undefined reference to
'mtsGenericObjectProxy<vctDynamicMatrix<double> >::Services() const'



If I change the matrix to mts then it works:
void SetMat(const mtsDoubleMat &mat) { m = mat};

**Comment by pkazanzides** [comment]
Yes, I also had this problem with the UR5 SAW component.  I don't know why `vctDynamicMatrix` doesn't work -- it is wrapped in `mtsGenericObject.h`.  I would close this issue, and add a new one about `vctDynamicMatrix`.

**Comment by marcinbalicki** [comment]
We can close the issue if mts data types are not going to be used directly.
