### ISSUE TITLE
cmnPath: Couldn't find file "config.GCM" in path $CISSTBUILD_DIR/cisst/share/cisst-1.0.2/cisstMultiTask/Ice

### ISSUE THREAD

**Issue by pchalas1** [jhu-cisst/cisst#23]
This error is displayed on launching cisstGlobalComponentManager.

config.GCM is being searched in cisst-1.0.2 instead of cisst-1.0

**Comment by adeguet1** [comment]
Fixed in fc93ae6c235b86cf0c18fd0ec7940a92af4d0094
