### ISSUE TITLE
cisstNumericalTests error on nmrConstraintOptimizer

### ISSUE THREAD

**Issue by adeguet1** [jhu-cisst/cisst#25]
Output of tests:
```sh
!!!FAILURES!!!
Test Results:
Run:  119   Failures: 1   Errors: 0


1) test: nmrConstraintOptimizerTest::TestSolve (F) line: 142 /Users/anton/devel/cisst-saw/cisst/cisstNumerical/tests/nmrConstraintOptimizerTest.cpp
equality assertion failed
- Expected: 4
- Actual  : 0
```

**Comment by pwilken3** [comment]
I found some problems in the error checking of nmrConstraintOptimizer's solve. It was assuming the slacks weren't factored into the size of dq, and so was comparing values against dq.size() + Slacks. I changed these expressions to just assess the size of dq.
