### ISSUE TITLE
cisstOSAbstraction Compiler errors on OS X

### ISSUE THREAD

**Issue by ahundt** [jhu-cisst/cisst#28]
I think some incorrect or non cross platform types were used in some cisstOSAbstraction code. Errors are below.

```
cisstOSAbstraction Group
Semantic Issue Group
/Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstOSAbstraction/code/osaSocket.cpp:437:30: Non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list
/Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstOSAbstraction/code/osaSocket.cpp:437:30: Insert an explicit cast to silence this issue
/Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstOSAbstraction/code/osaSocket.cpp:561:34: Non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list
/Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstOSAbstraction/code/osaSocket.cpp:561:34: Insert an explicit cast to silence this issue
/Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstOSAbstraction/code/osaSocket.cpp:740:34: Non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list
/Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstOSAbstraction/code/osaSocket.cpp:740:34: Insert an explicit cast to silence this issue
```

**Comment by ahundt** [comment]
this may fix the problem for the moment though it probably isn't the most correct way to do it:

``` c++

    long sec = static_cast<long>(floor(timeoutSec));
    long usec = static_cast<long>(floor( (timeoutSec - sec) *1e6));
#ifdef __APPLE__

    timeval timeout;
    timeout.tv_sec = sec;
    timeout.tv_usec = usec;
#else
    timeval timeout = { sec, usec };
#endif
```

Also if you make that change you should consider a very small function rather than the same code in 3 places.

**Comment by ahundt** [comment]
bump, this issue is still pending

**Comment by pkazanzides** [comment]
Would the following code work?

```c++
#if (CISST_OS == CISST_DARWIN)
    time_t sec = static_cast<time_t>(floor(timeoutSec));
    suseconds_t usec = static_cast<suseconds_t>((timeoutSec - sec) * 1e6);
#else
    long sec = static_cast<long>(floor(timeoutSec));
    long usec = static_cast<long>((timeoutSec - sec) * 1e6);
#endif
    timeval timeout = { sec, usec };
```

I believe the first code block would apply to Linux as well; perhaps to all operating systems except Windows.

**Comment by ahundt** [comment]
Unfortunately that version wouldn't work because timeval is defined slightly differently on darwin and the bracket notation didn't seem to compile if I recall correctly.

**Comment by ahundt** [comment]
It could potentially be the following, though I'm not sure how the CISST_DARWIN flag would work on ios:

```
    long sec = static_cast<long>(floor(timeoutSec));
    long usec = static_cast<long>(floor( (timeoutSec - sec) *1e6));

#if (CISST_OS == CISST_DARWIN)
    timeval timeout;
    timeout.tv_sec = sec;
    timeout.tv_usec = usec;
#else
    timeval timeout = { sec, usec };
#endif
```

**Comment by pkazanzides** [comment]
The way I read the compiler output, the problem is not with the bracket notation, but rather with the attempt to do an implicit typecast when using the bracket notation.  Please try the code I suggested on your Mac -- I don't have one to try it out.

**Comment by ahundt** [comment]
can we try to move this forward? Resolving these bugs would allow me to use cisst as a library installed on my OS rather than as a directory within my build tree.

**Comment by pkazanzides** [comment]
Try again with the latest checkin (devel branch). Compiled successfully on Windows VS 2008, Ubuntu 12.04 (gcc 4.6.3), and QNX.

**Comment by ahundt** [comment]
This does not work on OS X, partially because  suseconds_t  is not a defined type. Furthermore, there are two additional places where the code breaks that were missed by the patch.

The image below shows the lines and changes to the files necessary to work on OS X:
<img width="1268" alt="patch for os x" src="https://cloud.githubusercontent.com/assets/55744/9701448/9274d960-53f7-11e5-90d2-a216f9155f8b.png">

**Comment by pkazanzides** [comment]
If not `suseconds_t` and `time_t`, what types does Mac OSX use?  If we are going to do conditional compilation for Mac, we might as well use the correct types (I doubt it uses `long`).

**Comment by ahundt** [comment]
nevermind, I patched it to work. suseconds_t seems to be ok
