### ISSUE TITLE
Git workflow for SAW components is not documented

### ISSUE THREAD

**Issue by auneri** [jhu-cisst/cisst#31]
I understand that the **master** branch is stable, whereas the **devel** branch is used for normal commits, but what is the convention for updating the master? i.e., who is responsible for merging, is there a schedule to it, is it tied to release tags, etc..

Could not find any help on wiki, under development guidelines.

**Comment by ahundt** [comment]
I'm aware they are using a workflow based on git-flow, if that helps. I also believe @adeguet1 handles releases.

**Comment by pkazanzides** [comment]
Actually, we decided to define a development workflow for a larger body of LCSR software, which is documented here:  http://jhu-lcsr.github.io/dev-model/.  Note that most cisst/saw `README.md` files contain a link to the main LCSR software page, http://jhu-lcsr.github.io/software/.  We are using the "proto versioning" model.

The one thing not yet documented is who are the maintainers for each repository.  Clearly, @adeguet1 should be the maintainer for cisst and the dvrk software.  For SAW components, I think others could take on maintenance responsibilities, especially when the SAW component depends on specific hardware.
