### ISSUE TITLE
robManipulator memory leak 

### ISSUE THREAD

**Issue by zchen24** [jhu-cisst/cisst#39]
Here is my test code: 

```cpp
void test()
{
  vctDoubleVec jnt_pos(6, 0.0);
  vctFrm4x4    cpos;
  robManipulator rob("/path/to/simpsm.rob");
  cpos = rob.ForwardKinematics(jnt_pos);
}

int main()
{
  for (size_t i = 0; i < 10; i++)
  {
    test();
  }
}
```

Valgrind output 

```
==17464== Memcheck, a memory error detector
==17464== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==17464== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==17464== Command: ./testrob
==17464== 
==17464== 
==17464== HEAP SUMMARY:
==17464==     in use at exit: 79,744 bytes in 41 blocks
==17464==   total heap usage: 2,426 allocs, 2,385 frees, 358,558 bytes allocated
==17464== 
==17464== LEAK SUMMARY:
==17464==    definitely lost: 1,120 bytes in 20 blocks
==17464==    indirectly lost: 5,920 bytes in 20 blocks
==17464==      possibly lost: 0 bytes in 0 blocks
==17464==    still reachable: 72,704 bytes in 1 blocks
==17464==         suppressed: 0 bytes in 0 blocks
==17464== Rerun with --leak-check=full to see details of leaked memory
==17464== 
==17464== For counts of detected and suppressed errors, rerun with: -v
==17464== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 2 from 2)
```

**Comment by zchen24** [comment]
@simonleonard Can you help review this fix? Thanks. 

Zihan

**Comment by adeguet1** [comment]
travis is not happy: https://travis-ci.org/jhu-cisst/cisst/builds/86840047


---
Anton Deguet
410-790-0456
www.lcsr.jhu.edu

**Comment by zchen24** [comment]
@adeguet1  I was using --amend to fix my commit message and used git push -f to force update the cisst repository. Travis is checking out a commit that does not exist in the repo anymore ....

**Comment by simonleonard** [comment]
diff --git a/cisstRobot/code/robManipulator.cpp b/cisstRobot/code/robManipulator.cpp
index 97e7bb3..1da65c9 100644
--- a/cisstRobot/code/robManipulator.cpp
+++ b/cisstRobot/code/robManipulator.cpp
@@ -136,10 +136,12 @@ void free_rmatrix(double** m, long nrl, long ncl){
 }
 
 robManipulator::robManipulator( const vctFrame4x4<double>& Rtw0 )
+  : Jn(NULL),Js(NULL)
 {  this->Rtw0 = Rtw0;  }
 
 robManipulator::robManipulator( const std::string& linkfile,
-                                const vctFrame4x4<double>& Rtw0 ){
+                                const vctFrame4x4<double>& Rtw0 )
+  : Jn(NULL),Js(NULL){
 
   this->Rtw0 = Rtw0;
 
@@ -151,7 +153,8 @@ robManipulator::robManipulator( const std::string& linkfile,
 }
 
 robManipulator::robManipulator( const std::vector<robKinematics *> linkParms,
-                                const vctFrame4x4<double>& Rtw0 ){
+                                const vctFrame4x4<double>& Rtw0 )
+  : Jn(NULL),Js(NULL){
 
   this->Rtw0 = Rtw0;
 
@@ -162,8 +165,9 @@ robManipulator::robManipulator( const std::vector<robKinematics *> linkParms,
   }
 }
 
-robManipulator::~robManipulator()
-{
+robManipulator::~robManipulator(){
+  if( Jn != NULL ){ free_rmatrix(Jn, 0, 0); }
+  if( Js != NULL ){ free_rmatrix(Js, 0, 0); }
 }

**Comment by simonleonard** [comment]
Fixed

**Comment by ahundt** [comment]
might be wise to avoid -f and ammending commit messages on shared repositories... can be risky
