### ISSUE TITLE
cmnLogger issue in conditional statement

### ISSUE THREAD

**Issue by pkazanzides** [jhu-cisst/cisst#45]
The following code does not produce the expected result:

```
if (condition)
   CMN_LOG_RUN_VERBOSE << "Some text" << std::endl;
else {
   // some more code
}
```

This appears to be due to the macro used to define `CMN_LOG` (note that `CMN_LOG_RUN_VERBOSE` just calls `CMN_LOG` with a specified `lod`):

```
 #define CMN_LOG(lod) \
  if (cmnLogger::GetMask() & cmnLogger::GetMaskFunction() & lod) \
    ((cmnLODOutputMultiplexer(cmnLogger::GetMultiplexer(), lod).Ref()) << cmnLogLevelToString(lod) << " ")
```
Simplifying the above, `CMN_LOG(lod)` essentially expands to the following:
```
if (filterTrue)
   cmnLODOutputMultiplexerRef << user_string << " "
```
Thus, the original code is compiled as follows, where the `else` is indented to better indicate the problem:
```
if (condition)
   if (filterTrue)
       cmnLODOutputMultiplexerRef << "Some text" << " " << std::endl;
   else {
      // some more code
   }
```
I believe the fix would be to put braces around the entire `CMN_LOG` macro, e.g.:
```
 #define CMN_LOG(lod) \
  { if (cmnLogger::GetMask() & cmnLogger::GetMaskFunction() & lod) \
    ((cmnLODOutputMultiplexer(cmnLogger::GetMultiplexer(), lod).Ref()) << cmnLogLevelToString(lod) << " ") }
```

**Comment by adeguet1** [comment]
Interestingly, gcc gives this warning:
```
/home/anton/catkin_ws/src/cisst-saw/cisst/cisstCommon/tests/cmnLogLoDTest.cpp:100:12: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
```
There were 4 of these in cisst, 2 in cisstMultiTask, 2 in cisstRobot.

Unfortunately adding braces in the macro doesn't solve the issue.  The macro is used like this:
```c++
   CMN_LOG(level) << "some text" << std::end;
```

With the braces, this expends as:
```c++
  { if (condition) outputStream << } "some text" << std::endl;
```
which won't compile.

We can change the macro a bit to avoid the bug (I think?) but still triggers the gcc warning:
```c++
   // current logic
  #define log(level) \\
  if (needToLog(level)) outputStream <<

  // new logic
  #define log(level) \\
  if (!needToLog(level)) ; else outputStream <<
```
This is a bit better but programmers should still use braces to avoid the gcc warnings.

**Comment by pkazanzides** [comment]
This fix seems fine.

**Comment by adeguet1** [comment]
In aae4bba0da0387d6f91380e890a7ce37b43a668e:
* applied same logic CMN_LOG_CLASS macro.
* tracked most `if (cond) CMN_LOG ...` calls and added braces to avoid gcc warnings.   Behavior is correct in any case but warnings can be alarming

Changes have been merged in `devel` branch.
