### ISSUE TITLE
catkin build fails

### ISSUE THREAD

**Issue by Nikollao** [jhu-cisst/cisst#47]
I want to install dvrk-ros in Ubuntu. I clone the cisst-saw files and when I use catkin build, I get errors. The files fail to be cloned and i only manage to successfully install 14 out of 30 packages. This occurs with the master branch. In the devel branch, I get a different error:

<img width="1214" alt="error building cisst-saw devel" src="https://user-images.githubusercontent.com/28340787/31822970-7564fc10-b5a2-11e7-8575-878cdae32854.png">

Does anyone have any suggestions how to overcome this problem and install the dvrk?

Thanks

Nick

**Comment by Nikollao** [comment]
I managed to solve the problem. Currently, there is a bug in the master branch, so if you want to install dvrk and cisst-saw, you need to clone from the devel branch.

git clone -b devel https://github.com/jhu-cisst/cisst-saw --recursive (cisst-saw files)
git clone -b devel https://github.com/jhu-dvrk/dvrk-ros (dvrk files)

**Comment by adeguet1** [comment]
I believe this has been fixed in release 1.0.9.
