### ISSUE TITLE
catkin_make err

### ISSUE THREAD

**Issue by dbdxnuliba** [jhu-cisst/cisst#80]
Make Error at cisst/cmake/cisstInternalMacros.cmake:69 (message):
  cisst_set_package_settings: value for variable INCLUDE_DIRECTORIES provided
  for package cisstNetlib used by library cisstNumerical is not properly
  defined
Call Stack (most recent call first):
  cisst/cisstNumerical/CMakeLists.txt:33 (cisst_set_package_settings)

CMake Error at cisst/cmake/cisstInternalMacros.cmake:69 (message):
  cisst_set_package_settings: value for variable LIBRARIES provided for
  package cisstNetlib used by library cisstNumerical is not properly defined
Call Stack (most recent call first):
  cisst/cisstNumerical/CMakeLists.txt:34 (cisst_set_package_settings)

**Comment by adeguet1** [comment]
We do not support catkin_make and don't plan to.  To build the cisst libraries on Linux with ROS tools, please use the python catkin build tools. i.e. `catkin build`.   To note, once you've used `catkin_make` in a workspace, the workspace won't be compatible with `catkin build` anymore so you'll have to start from a clean workspace.   See https://github.com/jhu-cisst/cisst/wiki/Compiling-cisst-and-SAW-with-CMake#13-building-using-catkin-build-tools-for-ros
