### ISSUE TITLE
ROSToCISST missing matrix functionality (std_msgs::Float64MultiArray ---> vctDoubleVec)

### ISSUE THREAD

**Issue by dusevitch** [jhu-cisst/cisst#89]
Could we add:
`void mtsROSToCISST(const std_msgs::Float64MultiArray & rosData, vctDoubleVec & cisstData);` ?

Trying to run the below, but I noticed the above doesn't exist in `mtsROSToCISST.h`, although it is in  `mtsCISSTToROS.h`.  My code seems to break when I run this for any matrix writing CISST-ROS functionality, and I'm guessing this is the issue?
`m_subscribers_bridge->AddSubscriberToCommandWrite<vctDoubleMat, std_msgs::Float64MultiArray>
      (_required_interface_name, "SetJacobianWeights", _clean_namespace + "/set_jacobian_weights");`

**Comment by adeguet1** [comment]
Can you try the devel branch for cisst-ros?  See also https://github.com/jhu-cisst/cisst-ros/commit/e12bbe3d245d8e9b42dc40d5aeb6156ddb2c6857#

**Comment by dusevitch** [comment]
Looks like you changed the properties of `clean_namespace`.  Should this be declared with the namespace now?
```
/home/david/bigss/catkin_ws/src/cisst-saw/sawNDITracker/ros/mts_ros_crtk_ndi_bridge.cpp: In member function ‘void mts_ros_crtk_ndi_bridge::bridge(const string&, const string&, double, double)’:
/home/david/bigss/catkin_ws/src/cisst-saw/sawNDITracker/ros/mts_ros_crtk_ndi_bridge.cpp:36:5: error: ‘clean_namespace’ was not declared in this scope
     clean_namespace(_clean_namespace);
```

**Comment by adeguet1** [comment]
You might want to use the latest devel for sawNDITracker too :-) https://github.com/jhu-saw/sawNDITracker/commit/a0bc48c9280ae989f4dc7090315cb6531d34e30f

**Comment by dusevitch** [comment]
Ha whoops. Works great. Thanks!
